format = """
[▒░](bg:#a3aed2 fg:#090c0c)\
$os\
[](fg:#a3aed2 bg:#1a5fb4)\
$directory\
[](fg:#1a5fb4 bg:#3584e4)\
$git_branch\
$git_status\
[](fg:#3584e4 bg:#212736)\
$nodejs\
$package\
$docker_context\
$rust\
$golang\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:#212736 bg:#1d2230)\
$cmd_duration\
$time\
[ ](fg:#1d2230)\
\n$character
"""

# ───────── OS ─────────

[os]
disabled = false
style = "bg:#a3aed2 fg:#090c0c"
format = "[ $symbol ]($style)"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
Fedora = "󰣛"
Gentoo = "󰣨"

# ───────── Directory ─────────

[directory]
style = "fg:#e3e5e5 bg:#1a5fb4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# ───────── Git ─────────

[git_branch]
symbol = ""
style = "fg:#e3e5e5 bg:#3584e4"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:#e3e5e5 bg:#3584e4"
format = "[ $all_status$ahead_behind ]($style)"

# ───────── Stack ─────────

[nodejs]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = "[ $symbol $version ]($style)"

[package]
symbol = "󰏗"
style = "fg:#f7c873 bg:#212736"
format = "[ $symbol $version ]($style)"

[docker_context]
symbol = ""
style = "fg:#0db7ed bg:#212736"
format = "[ $symbol $context ]($style)"

[python]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = "[ $symbol $version ]($style)"

# ───────── UX ─────────

[cmd_duration]
min_time = 2000
style = "fg:#fab387 bg:#1d2230"
format = "[ 󱦟 $duration ]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:#a0a9cb bg:#1d2230"
format = "[  $time ]($style)"

# ───────── Prompt ─────────

[character]
success_symbol = "[❯](fg:#769ff0)"
error_symbol = "[❯](fg:#ff6c6b)"
